#!/bin/bash
#SBATCH --partition=gpu
#SBATCH --gpus-per-node=1
#SBATCH --job-name=test_opt
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=04:00:00
#SBATCH --output=test_opt%A.out

# Define the MODEL variable
MODEL="enet"  # Change this to "enet", "unet" or "unetr" as needed

# activate the environment
source ai4mi/bin/activate
module load 2022
module load Python/3.10.4-GCCcore-11.3.0

python -O main.py --model "$MODEL" --dataset SEGTHOR --mode full --epoch 100 --dest results/segthor_${MODEL}_adam/ce --gpu --metric dice --optim adam
python plot.py --metric_file results/segthor_${MODEL}_adam/ce/loss_tra.npy --dest results/segthor_${MODEL}_adam/ce/loss_tra.png
python plot.py --metric_file results/segthor_${MODEL}_adam/ce/dice_val.npy --dest results/segthor_${MODEL}_adam/ce/dice_val.png

python -O main.py --model "$MODEL" --dataset SEGTHOR --mode full --epoch 100 --dest results/segthor_${MODEL}_adamW/ce --gpu --metric dice --optim adamW
python plot.py --metric_file results/segthor_${MODEL}_adamW/ce/loss_tra.npy --dest results/segthor_${MODEL}_adamW/ce/loss_tra.png
python plot.py --metric_file results/segthor_${MODEL}_adamW/ce/dice_val.npy --dest results/segthor_${MODEL}_adamW/ce/dice_val.png

